// src/pages/versions/index.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { invoke } from '@tauri-apps/api/tauri'

const installedVersions = ref<string[]>([])
const updateInstalledVersions = () => {
  invoke('list_versions')
    .then(v => installedVersions.value = v as string[])
    .catch((e: string) => console.error(e))
}

onMounted(updateInstalledVersions)
</script>

<template>
  <div class="flex flex-col gap-y-4 my-auto min-w-64">
    <h1 class="text-3xl text-center my-4">
      Installed Versions
    </h1>
    <div
      v-for="version in installedVersions"
      :key="version"
      class="p-2 flex items-center justify-between border-1 rounded-lg shadow-md"
    >
      <Version :version="version" @update="updateInstalledVersions" />
    </div>
    <router-link to="/add-version">
      <CustomButton center primary>
        Add a version
      </CustomButton>
    </router-link>
  </div>
</template>

// src/lib/Versions.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import {
    getAvailableVersions,
    getInstalledVersions,
    installVersion,
    removeVersion,
  } from "../api";
  import type { Version } from "../api";

  let installedVersions: Version[] = [];
  const updateInstalledVersions = () => {
    getInstalledVersions().then((versions) => {
      installedVersions = versions;
    });
  };

  let availableVersions: Version[] = [];
  const updateAvailableVersions = () => {
    getAvailableVersions().then((versions) => {
      availableVersions = versions;
    });
  };

  const install = (version: Version) => {
    installVersion(version).then(updateInstalledVersions);
  };

  const remove = (version: Version) => {
    removeVersion(version).then(updateInstalledVersions);
  };

  onMount(() => {
    updateInstalledVersions();
    updateAvailableVersions();
  });
</script>

<div class="flex gap-x-8">
  {#if installedVersions.length}
    <div class="flex-1">
      <h1 class="text-3xl text-center mb-8">Installed Versions</h1>
      <div
        class="border-2 rounded-3xl p-2 overflow-y-auto h-64 flex flex-col divide-y"
      >
        {#each installedVersions as version}
          <div class="p-2 flex justify-between">
            {version.id}
            <button
              class="px-2 py-1 bg-red-500 text-white rounded-full"
              on:click={(e) => remove(version)}>Remove 🗑</button
            >
          </div>
        {/each}
      </div>
    </div>
  {/if}
  <div class="flex-1">
    <h1 class="text-3xl text-center mb-8">Available Versions</h1>
    <div
      class="border-2 rounded-3xl p-2 overflow-y-auto h-64 flex flex-col divide-y"
    >
      {#each availableVersions as version}
        <div class="p-2 flex justify-between">
          {version.type === "release" ? "✅" : "🔥"}
          {version.type}
          {version.id}
          <button
            class="px-2 py-1 bg-green-500 text-white rounded-full"
            on:click={(e) => install(version)}>Install ➕</button
          >
        </div>
      {/each}
    </div>
  </div>
</div>
