// src/App.vue
<template>
  <div class="p-4 flex flex-col justify-between h-screen">
    <nav class="flex justify-between">
      <div>
        <router-link to="/">🏠</router-link>
      </div>
      <div>
        <router-link to="/about">?</router-link>
      </div>
    </nav>

    <main class="m-auto">
      <router-view />
    </main>

    <footer class="text-center min-h-max">
      MIT Licensed | © 2021 Manuel Quarneti
    </footer>
  </div>
</template>

// src/App.svelte
<script lang="ts">
  import Home from "./lib/Home.svelte";
  import Versions from "./lib/Versions.svelte";

  let selectedView: any = Home;
</script>

<div class="p-4 flex flex-col justify-between h-screen">
  <nav class="flex justify-between">
    <button on:click={(e) => (selectedView = Home)}>🏠</button>
  </nav>

  <main class="flex flex-col items-center justify-center">
    <svelte:component
      this={selectedView}
      on:goToVersions={(e) => (selectedView = Versions)}
    />
  </main>

  <footer class="mx-auto">MIT Licensed | © 2021 Manuel Quarneti</footer>
</div>
